// <auto-generated />
using System;
using LOBCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LOBCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("LOBCore.Models.CommUserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CommUserGroups");
                });

            modelBuilder.Entity("LOBCore.Models.CommUserGroupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CommUserGroupId");

                    b.Property<string>("Email");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("CommUserGroupId");

                    b.ToTable("CommUserGroupItems");
                });

            modelBuilder.Entity("LOBCore.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("LOBCore.Models.ExceptionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CallStack");

                    b.Property<string>("DeviceModel");

                    b.Property<string>("DeviceName");

                    b.Property<DateTime>("ExceptionTime");

                    b.Property<string>("Message");

                    b.Property<string>("OSType");

                    b.Property<string>("OSVersion");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExceptionRecords");
                });

            modelBuilder.Entity("LOBCore.Models.LeaveForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginTime");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndTime");

                    b.Property<int?>("LeaveFormTypeId");

                    b.Property<int>("TotalHours");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LeaveFormTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveForms");
                });

            modelBuilder.Entity("LOBCore.Models.LeaveFormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LeaveFormTypes");
                });

            modelBuilder.Entity("LOBCore.Models.LobUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("LobUsers");
                });

            modelBuilder.Entity("LOBCore.Models.NotificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OSType");

                    b.Property<DateTime>("RegistrationTime");

                    b.Property<string>("Token");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationTokens");
                });

            modelBuilder.Entity("LOBCore.Models.CommUserGroupItem", b =>
                {
                    b.HasOne("LOBCore.Models.CommUserGroup", "CommUserGroup")
                        .WithMany()
                        .HasForeignKey("CommUserGroupId");
                });

            modelBuilder.Entity("LOBCore.Models.ExceptionRecord", b =>
                {
                    b.HasOne("LOBCore.Models.LobUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LOBCore.Models.LeaveForm", b =>
                {
                    b.HasOne("LOBCore.Models.LeaveFormType", "LeaveFormType")
                        .WithMany()
                        .HasForeignKey("LeaveFormTypeId");

                    b.HasOne("LOBCore.Models.LobUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LOBCore.Models.LobUser", b =>
                {
                    b.HasOne("LOBCore.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("LOBCore.Models.NotificationToken", b =>
                {
                    b.HasOne("LOBCore.Models.LobUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
